export const LIST_MODIFIERS = "modifiers/LIST_MODIFIERS"
export const LIST_MODIFIERS_SUCCESS = "modifiers/LIST_MODIFIERS_SUCCESS"
export const LIST_MODIFIERS_ERROR = "modifiers/LIST_MODIFIERS_ERROR"

export const ADD_MODIFIERS = "modifiers/ADD_MODIFIERS"
export const ADD_MODIFIERS_SUCCESS = "modifiers/ADD_MODIFIERS_SUCCESS"
export const ADD_MODIFIERS_ERROR = "modifiers/ADD_MODIFIERS_ERROR"

export const UPDATE_MODIFIERS = "modifiers/UPDATE_MODIFIERS"
export const UPDATE_MODIFIERS_SUCCESS = "modifiers/UPDATE_MODIFIERS_SUCCESS"
export const UPDATE_MODIFIERS_ERROR = "modifiers/UPDATE_MODIFIERS_ERROR"

export const DELETE_MODIFIERS = "modifiers/DELETE_MODIFIERS"
export const DELETE_MODIFIERS_SUCCESS = "modifiers/DELETE_MODIFIERS_SUCCESS"
export const DELETE_MODIFIERS_ERROR = "modifiers/DELETE_MODIFIERS_ERROR"

export const DETAIL_MODIFIERS = "modifiers/DETAIL_MODIFIERS"
export const DETAIL_MODIFIERS_SUCCESS = "modifiers/DETAIL_MODIFIERS_SUCCESS"
export const DETAIL_MODIFIERS_ERROR = "modifiers/DETAIL_MODIFIERS_ERROR"

export const SET_SELECTED = "modifiers/SET_SELECTED"
export const REMOVE_SELECTED = "modifiers/REMOVE_SELECTED"

export const RESET_ERROR = "modifiers/RESET_ERROR"
